dev:
  name: dev
  enable: false
git:
  name: git
  enable: true
mmd:
  name: mmd
  enable: true
  labels: []
  defaultLabel:
    author: 目棃
    filename: README
    description: 说明文档
pip:
  name: pip
  enable: true
rs:
  name: rs
  enable: true
update: 1727661143
